BEGIN', '

-- Revert previous (erroneous) sql files (47 & 48) ensuring records for Paraguay and South Sudan are not inserted twice
DELETE FROM imet.imet_pas WHERE country = 'PRY';
DELETE FROM imet.imet_pas WHERE country = 'SSD';
DELETE FROM imet.imet_countries WHERE iso3 = 'SSD';
INSERT into imet.imet_countries VALUES ('SS', 'SSD', 728, 'South Sudan', 'South Sudan', 'South Sudan');

-- Now insert correct records for Paraguay and South Sudan
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '242', 'Defensores del Chaco', 'II', '7207236439');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '244', 'Teniente Agripino Enciso', 'II', '422416814');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '245', 'Caazapa', 'II', '126994517');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '246', 'Cerro Cora', 'II', '56833544');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '247', 'Ybycui', 'II', '50602518');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '20983', 'Lago Ypacarai y Sus Humedales Adyacentes', 'IV', '369.47');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '20984', 'Cordillera Del Ybytyruzu', 'IV', '240');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '20987', 'Ñacunday', 'II', '20035903');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '20991', 'Mbaracayu', 'IV', '13.56');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '30045', 'Moises Santiago Bertoni', 'Ia', '1998526');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '37115', 'Del Bosque Mbaracayú', 'IV', '644058');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '61554', 'Medanos del Chaco', 'II', '6050757063');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '220266', 'Reserva de la Biosfera Bosque Mbaracayu', 'Not Applicable', '2800');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '317126', 'Yabebyry', 'Ib', '300');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '317127', 'Serrania de San Luis', 'II', '102825454');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '317128', 'Paso Bravo', 'II', '10061395');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '317131', 'Macizo Acahay', 'III', '25');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '902513', 'Reserva de la Biosfera del Chaco', 'Not Reported', '47072.5');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629386', 'Cerro Koi', 'III', '0.12');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629387', 'Cerro Chorori', 'III', '0.05');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629389', 'Saltos del Guairá', 'II', '9');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629392', 'Caverna Santa Elena', 'III', '0.354');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629395', 'Ñuguazu', 'IV', '2802664');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629397', 'Bosque Yvyraty', 'IV', '2.62');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629398', 'Caverna Kamba Hopo', 'III', '0.174859');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629399', 'Cerro Tres Cerros, Cav. 14 de Julio, Santa Caverna', 'III', '1398091');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629400', 'Cerro Morado, Caverna Ycua Pai', 'III', '0.771001');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629402', 'Capiibary', 'II', '30827087');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629403', 'Cerro Dos de Oro', 'V', '0.449582');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629404', 'Isla Susu y Sus Humedales', 'III', '81113155');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629405', 'Ycua Bolaños', 'V', '0.1');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629406', 'Carrizales del Parana', 'III', '90497757');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629407', 'Isla Carrizal', 'III', '25739029');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629408', 'Banco San Miguel y Bahía de Asunción', 'II', '60174');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629409', 'Refugio de Vida Silvestre Humedales del Bajo Chaco', 'IV', '85101113');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629410', 'Cañada El Carmen', 'IV', '39731124');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629411', 'Arcadia', 'IV', '50');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629412', 'Punie Paesoi', 'IV', '37.8');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629413', 'Yaguarete Porá', 'IV', '275088759');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629414', 'Palmar Quemado', 'IV', '94781886');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629416', 'Cerrados del Tagatiya', 'IV', '57');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629417', 'Tagatiya Mi', 'IV', '287688073');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629418', 'El Guayacán i, ii y iii', 'IV', '15093734');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629419', 'Piro''y', 'IV', '0.1337';
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629420', 'Laguna Blanca', 'IV', '8038741');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629421', 'Arroyo Tapiracuái', 'IV', '123.36');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629423', 'Tabucai', 'IV', '559004');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629424', 'Salto del Monday', 'V', '3.94');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629425', 'Itakyry', 'IV', '1.96');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629426', 'Maharishi', 'IV', '3424804');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629427', 'Maharishi II', 'IV', '0.776135');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629428', 'Yguazú', 'IV', '17853795');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629430', 'Edelira', 'IV', '9.54');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629431', 'Guyrati', 'IV', '38116121');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629434', 'Bosque Arary', 'IV', '0.515835');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629435', 'Chopí Sa''yju', 'IV', '7886882';
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629437', 'Reserva de Biosfera del Cerrado del Rio Apa', 'Not Reported', '2678363412');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629438', 'Cerro Chovoreca', 'II', '1,01764E+11';
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629440', 'Lote 1', 'IV', '5364122';
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629441', 'La Morena', 'IV', '18318383');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629443', 'Riacho Florida 2', 'IV', '11856736');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629444', 'Arrecife', 'IV', '74375435');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629445', 'Estrella', 'IV', '10193071');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629446', 'El Ceibo', 'IV', '58492974');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555629447', 'Villa Josefina', 'IV', '1807647');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555636653', 'Reserva de la Biosfera del Chaco', 'Not Applicable', '47072.5');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786024', 'Laguna Blanca', 'III', '1.57');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786025', 'Teniente 1° Adolfo Rojas Silva', 'IV', '47398712');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786026', 'Reserva de la Biosfera Itaipu', 'Not Applicable', '10474.38');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786027', 'Sagrado Corazon de Jesus', 'V', '0.092989');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786028', 'Ykua Santa', 'V', '0.0756');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786029', 'Cerro Bogarin', 'V', '221327');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786030', 'Ykua Ita y Ykua Chorrito', 'V', '0.0756');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786031', 'Laguna Vera y Humedales Adyacentes', 'V', '1084086');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786032', 'Mariscal Jose Felix Estigarribia', 'III', '0.07');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786033', 'Cerro Kavaju', 'V', '1108575');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786034', 'Cerro Cristo Rey', 'II', '0.234515');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786035', 'Estero Yetyty', 'V', '232302754');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786036', 'Arroyo Tobati', 'V', '43.71');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786037', 'Arroyo Yukyry', 'V', '33590549');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786038', 'Pajaro Campana', 'II', '1726107');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786039', 'Laguna Yrendy', 'V', '16403');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786040', 'Toldo Cue', 'IV', '10176745');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786041', 'Ita Poty', 'IV', '6721199');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786042', 'Generico Reserva Natural (RC4-Zevallos Cué)', 'IV', '0.329802');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786043', 'Complejo de Lagunas Méndez y Sisi', 'III', '7.76');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786044', 'Guasú Pukú', 'IV', '3452943');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786045', '1a División de Caballeria - Cuartel General', 'IV', '121867662');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786046', 'Coronel Valóis Rivarola', 'IV', '9814963');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786047', 'Tupanoi', 'IV', '20302034');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786048', 'Dios Creador Karaja Tapyi', 'IV', '0.179382');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786049', 'Divino Niño Jesus', 'IV', '0.722225');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786050', 'Aguapey', 'IV', '13132207');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786051', 'Campo Iris', 'IV', '35');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786052', 'Doña Clea', 'IV', '20828067');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786053', 'Yrenda', 'IV', '26');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786054', 'Guarapi', 'IV', '0.893016');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786055', 'Mainumby', 'IV', '376903994');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786056', 'Pozuelo', 'IV', '55212491');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786057', 'Tsm', 'IV', '11601502');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555786058', 'Parque Guasu Metropolitano', 'IV', '1231427');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790156', 'Los Humedales de Cerro Tigre', 'II', '2568071');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790157', 'Arroyo Yuquyry', 'IV', '0.329648');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790158', 'San Jóse', 'V', '0.843');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790159', 'Mayor Infante Rivarola', 'IV', '1490019');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790160', 'Salto Ingles o Cascada Sapucai', 'V', '2411427');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790179', 'Tinfunque', 'IV', '1762724149');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790180', 'Kuriy', 'II', '20');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790181', 'Itabo', 'IV', '182931116');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790182', 'Limoy', 'IV', '22529869');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790183', 'Tati Yupi', 'IV', '38661464');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790184', 'San Rafael', 'II', '780');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790185', 'Rio Negro', 'II', '1227737745');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790186', 'Carapa', 'IV', '43825545');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790187', 'Ka''i Rague', 'IV', '18598833';
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790188', 'Lago Ypoa', 'IV', '1190.06');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790189', 'Bella Vista', 'II', '73.11');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790190', 'Pikyry', 'IV', '2866803');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790191', 'Arroyo Blanco', 'IV', '57144326');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790192', 'Morombi', 'IV', '250');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790193', 'Cerro Cabrera - Timane', 'II', '1250614274');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790194', 'Cerro Lambare', 'V', '0.112366');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790195', 'Yacyreta', 'IV', '63008694');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790196', 'Jukyty Guasú', 'II', '0.04');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790197', 'Huasipungo', 'II', '0.780284');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790198', 'Toro Mocho', 'IV', '180');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790199', 'Ypeti', 'IV', '135923385');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790200', 'Tapyta', 'IV', '47370088');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790201', 'Yvyty rokái', 'IV', '48648107');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790202', 'Arroyo Aguapey', 'IV', '86240217');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('PRY', '555790203', 'Ñuguazu', 'IV', '500');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '555583105', 'Bire Kapatuos', 'VI', '5');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '555583106', 'Fanyikang', 'VI', '480');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '555583107', 'Loelle', 'VI', '10963');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '555583108', 'Boma Extension', 'II', '4887');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '555583109', 'Nimule Buffer Zone', 'II', '0');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '555583110', 'Badingilo Extension', 'II', '7724');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '555583111', 'Numatina', 'VI', '2100');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '903', 'Southern', 'II', '22800');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '904', 'Nimule', 'II', '200');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '1368', 'Ez Zeraf', 'VI', '8000');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '1369', 'Kidepo', 'VI', '1200');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '1370', 'Bangangai', 'VI', '170');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '1371', 'Boma', 'II', '20000');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '1372', 'Shambe', 'II', '620');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '1373', 'Ashana', 'VI', '900');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '1374', 'Juba', 'VI', '200');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '1377', 'Mbarizunga', 'VI', '10');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '2337', 'Badingilo', 'II', '16000');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '10735', 'Chelkou', 'VI', '5500');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '10736', 'Boro', 'VI', '1500');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '10737', 'Lantoto', 'II', '760');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '10738', 'Meshra', 'VI', '4500');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '14089', 'Imatong', 'V', '1100');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '18758', 'Lake Ambadi', 'IV', '1500');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '18759', 'Lake No', 'IV', '1000');
INSERT INTO imet.imet_pas (country, wdpa_id, name, iucn_category, area, global_id) VALUES ('SSD', '18763', 'Lake Abiad', 'IV', '5000');

COMMIT', '